logging:
  config: classpath:logback-dev.xml

spring:
  application:
    name: pokerunner

  datasource:
    url: jdbc:mysql://133.186.215.243:3306/pokerunner
    username: root
    password: poke1234$
    driver-class-name: com.mysql.cj.jdbc.Driver
