logging:
  config: classpath:logback-dev.xml

spring:
  config:
    import: "db.properties"
  application:
    name: pokerunner

  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
