logging:
  config: classpath:logback-dev.xml

spring:
  config:
    import: "key.properties"
  application:
    name: pokerunner
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/pokerunner
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

nhn:
  map:
    url: https://kr1-maps.api.nhncloudservice.com/maps/v3.0/appkeys/${nhn.key}